- name: set ES_PATH_CONF
  lineinfile:
    path: /etc/sysconfig/elasticsearch
    line: ES_PATH_CONF=/etc/elasticsearch/{{es_generator_instance_name}}

- name: generate certificate with certutil
  command: sh /usr/share/elasticsearch/bin/elasticsearch-certutil cert --out {{ certificate_path }} --pass ""

- name: set certificate file permissions
  become_user: elasticsearch
  file:
    path: "{{ certificate_path }}"
    owner: "{{ es_user }}"
    mode: 0640

- name: unset ES_PATH_CONF
  lineinfile:
    path: /etc/sysconfig/elasticsearch
    state: absent
    line: ES_PATH_CONF=/etc/elasticsearch/{{es_generator_instance_name}}