---
# tasks file for generate-certificate
- name: set certificate path
  set_fact:
    certificate_path: /etc/elasticsearch/{{es_generator_instance_name}}/{{certificate_file_name}}

- name: remove existing certificate if override is desired
  file:
    state: absent
    path: "{{ certificate_path }}"
  when: override_existing_certificate

- name: check if certificate file exists
  stat:
    path: "{{ certificate_path }}"
  register: certificate_file_stats

- name: notify if certificate already exists
  debug:
    msg: The certificate file already exists in path {{ certificate_path }}.
  when: certificate_file_stats.stat.exists

- name: set ES_PATH_CONF
  lineinfile:
    path: /etc/sysconfig/elasticsearch
    line: ES_PATH_CONF=/etc/elasticsearch/{{es_generator_instance_name}}

- name: generate certificate file and set its permissions
  include: generate_certificate_file.yml
  when: not certificate_file_stats.stat.exists

- name: unset ES_PATH_CONF
  lineinfile:
    path: /etc/sysconfig/elasticsearch
    state: absent
    line: ES_PATH_CONF=/etc/elasticsearch/{{es_generator_instance_name}}